
import type { Patient } from './types'

export const patients: Patient[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    abhaId: '12-3456-7890-1234',
    age: 68,
    gender: 'Female',
    admissionDate: '2024-05-10',
    status: 'Reconciliation Pending',
    avatarUrl: 'https://picsum.photos/seed/patient1/100/100',
    vitals: [
      { date: '2024-05-10T08:00:00Z', systolic: 140, diastolic: 90, heartRate: 85, glucose: 180, weight: 75 },
      { date: '2024-05-11T08:00:00Z', systolic: 135, diastolic: 88, heartRate: 82, glucose: 172, weight: 75.2 },
      { date: '2024-05-12T08:00:00Z', systolic: 130, diastolic: 85, heartRate: 78, glucose: 165, weight: 74.8 },
      { date: '2024-05-13T08:00:00Z', systolic: 128, diastolic: 82, heartRate: 75, glucose: 158, weight: 74.5 },
    ],
    medications: {
      preAdmission: [
        { id: 'med1', name: 'Metformin', dosage: '500 mg', frequency: 'Twice a day', route: 'Oral' },
        { id: 'med2', name: 'Amlodipine', dosage: '5 mg', frequency: 'Once a day', route: 'Oral' },
      ],
      postDischarge: [
        { id: 'med1', name: 'Metformin', dosage: '500 mg', frequency: 'Twice a day', route: 'Oral', status: 'Unchanged' },
        { id: 'med3', name: 'Atorvastatin', dosage: '20 mg', frequency: 'Once a day', route: 'Oral', status: 'New' },
        { id: 'med4', name: 'Aspirin', dosage: '75 mg', frequency: 'Once a day', route: 'Oral', status: 'New' },
        { id: 'med2', name: 'Amlodipine', dosage: '10 mg', frequency: 'Once a day', route: 'Oral', status: 'Changed' },
      ],
    },
    alerts: [
      { id: 'alert1', type: 'Drug-Drug', severity: 'Warning', description: 'Aspirin and Warfarin have a potential interaction. Monitor INR levels.' },
      { id: 'alert2', type: 'Dose', severity: 'Info', description: 'Amlodipine dose increased from 5mg to 10mg.' },
    ],
    caregivers: [
      { id: 'care1', name: 'Rohan Sharma', relation: 'Son', phone: '+91-9876543210', avatarUrl: 'https://picsum.photos/seed/caregiver1/100/100', comprehensionStatus: 'Acknowledged' },
    ],
    abhaRecord: `Patient Name: Priya Sharma
ABHA ID: 12-3456-7890-1234
DOB: 1956-03-15
Allergies: Penicillin
Past Medical History: Type 2 Diabetes (diagnosed 2010), Hypertension (diagnosed 2015), Chronic Kidney Disease Stage 3.
Previous Surgeries: None.
Family History: Father had coronary artery disease.`,
    diagnosis: 'Unstable Angina (ICD-10: I20.0), Community Acquired Pneumonia',
    followUp: 'Follow up with Dr. Mehta in Cardiology OPD after 1 week. Contact hospital at 011-23456789 for appointments.',
    adherence: [
        { id: 'adh1', medicationId: 'med1', medicationName: 'Metformin', scheduledTime: '2024-05-18T08:00:00', status: 'Taken', actualTime: '2024-05-18T08:05:00', recoveryScore: 70 },
        { id: 'adh2', medicationId: 'med3', medicationName: 'Atorvastatin', scheduledTime: '2024-05-18T08:00:00', status: 'Taken', actualTime: '2024-05-18T08:05:00', recoveryScore: 70 },
        { id: 'adh3', medicationId: 'med4', medicationName: 'Aspirin', scheduledTime: '2024-05-18T08:00:00', status: 'Taken', actualTime: '2024-05-18T08:05:00', recoveryScore: 70 },
        { id: 'adh4', medicationId: 'med2', medicationName: 'Amlodipine', scheduledTime: '2024-05-18T08:00:00', status: 'Taken', actualTime: '2024-05-18T08:05:00', recoveryScore: 70 },
        { id: 'adh5', medicationId: 'med1', medicationName: 'Metformin', scheduledTime: '2024-05-18T20:00:00', status: 'Missed', recoveryScore: 65 },

        { id: 'adh6', medicationId: 'med1', medicationName: 'Metformin', scheduledTime: '2024-05-19T08:00:00', status: 'Taken', actualTime: '2024-05-19T08:15:00', recoveryScore: 80 },
        { id: 'adh7', medicationId: 'med3', medicationName: 'Atorvastatin', scheduledTime: '2024-05-19T08:00:00', status: 'Taken', actualTime: '2024-05-19T08:15:00', recoveryScore: 80 },
        { id: 'adh8', medicationId: 'med4', medicationName: 'Aspirin', scheduledTime: '2024-05-19T08:00:00', status: 'Taken', actualTime: '2024-05-19T08:15:00', recoveryScore: 80 },
        { id: 'adh9', medicationId: 'med2', medicationName: 'Amlodipine', scheduledTime: '2024-05-19T08:00:00', status: 'Taken', actualTime: '2024-05-19T08:15:00', recoveryScore: 80 },
        { id: 'adh10', medicationId: 'med1', medicationName: 'Metformin', scheduledTime: '2024-05-19T20:00:00', status: 'Pending', recoveryScore: 85 },

        { id: 'adh11', medicationId: 'med1', medicationName: 'Metformin', scheduledTime: '2024-05-20T08:00:00', status: 'Pending', recoveryScore: 90 },
        { id: 'adh12', medicationId: 'med3', medicationName: 'Atorvastatin', scheduledTime: '2024-05-20T08:00:00', status: 'Pending', recoveryScore: 90 },
      ],
    symptoms: [
      { id: 'sym1', date: '2024-05-18', symptom: 'Mild chest tightness', severity: 'Mild', notes: 'Occurred after walking up stairs. Lasted 2 minutes.', stress: 5, mood: 6, worry: 7 },
      { id: 'sym2', date: '2024-05-19', symptom: 'Shortness of breath', severity: 'Moderate', notes: 'Felt breathless after a short walk in the morning.', stress: 7, mood: 4, worry: 8 },
      { id: 'sym3', date: '2024-05-20', symptom: 'Feeling better', severity: 'Mild', notes: 'Feeling much better today, less breathless.', stress: 4, mood: 8, worry: 5 },
    ],
    egfr: 45, // Represents eGFR value for renal function
    lft: 'Slightly Elevated', // Represents Liver Function Test result
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    abhaId: '23-4567-8901-2345',
    age: 72,
    gender: 'Male',
    admissionDate: '2024-05-12',
    status: 'Discharged',
    avatarUrl: 'https://picsum.photos/seed/patient2/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: '',
    followUp: '',
    adherence: [],
    symptoms: [],
  },
  {
    id: '3',
    name: 'Anjali Devi',
    abhaId: '34-5678-9012-3456',
    age: 55,
    gender: 'Female',
    admissionDate: '2024-05-14',
    status: 'Admitted',
    avatarUrl: 'https://picsum.photos/seed/patient3/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: '',
    followUp: '',
    adherence: [],
    symptoms: [],
  },
  {
    id: '4',
    name: 'Vikram Singh',
    abhaId: '45-6789-0123-4567',
    age: 80,
    gender: 'Male',
    admissionDate: '2024-05-15',
    status: 'Reconciliation Pending',
    avatarUrl: 'https://picsum.photos/seed/patient4/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [{id: 'alert-ped', type: 'Dose', severity: 'Critical', description: 'High-risk medication for elderly. Verify dosage.'}],
    caregivers: [],
    abhaRecord: '',
    diagnosis: '',
    followUp: '',
    adherence: [],
    symptoms: [],
  },
    {
    id: '5',
    name: 'Suresh Gupta',
    abhaId: '56-7890-1234-5678',
    age: 65,
    gender: 'Male',
    admissionDate: '2024-05-16',
    status: 'Admitted',
    avatarUrl: 'https://picsum.photos/seed/patient5/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Acute Myocardial Infarction',
    followUp: 'Follow up in 1 week.',
    adherence: [],
    symptoms: [],
  },
  {
    id: '6',
    name: 'Lalita Iyer',
    abhaId: '67-8901-2345-6789',
    age: 78,
    gender: 'Female',
    admissionDate: '2024-05-17',
    status: 'Discharged',
    avatarUrl: 'https://picsum.photos/seed/patient6/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Congestive Heart Failure',
    followUp: 'Follow up in 2 weeks.',
    adherence: [],
    symptoms: [],
  },
  {
    id: '7',
    name: 'Ramesh Reddy',
    abhaId: '78-9012-3456-7890',
    age: 59,
    gender: 'Male',
    admissionDate: '2024-05-18',
    status: 'Admitted',
    avatarUrl: 'https://picsum.photos/seed/patient7/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Hypertensive Crisis',
    followUp: 'Follow up in 3 days.',
    adherence: [],
    symptoms: [],
  },
  {
    id: '8',
    name: 'Sunita Patil',
    abhaId: '89-0123-4567-8901',
    age: 62,
    gender: 'Female',
    admissionDate: '2024-05-18',
    status: 'Reconciliation Pending',
    avatarUrl: 'https://picsum.photos/seed/patient8/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Pneumonia',
    followUp: 'Follow up in 1 week.',
    adherence: [],
    symptoms: [],
  },
  {
    id: '9',
    name: 'Arun Joshi',
    abhaId: '90-1234-5678-9012',
    age: 75,
    gender: 'Male',
    admissionDate: '2024-05-19',
    status: 'Admitted',
    avatarUrl: 'https://picsum.photos/seed/patient9/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Chronic Obstructive Pulmonary Disease',
    followUp: 'Follow up in 1 month.',
    adherence: [],
    symptoms: [],
  },
  {
    id: '10',
    name: 'Gita Menon',
    abhaId: '01-2345-6789-0123',
    age: 81,
    gender: 'Female',
    admissionDate: '2024-05-20',
    status: 'Discharged',
    avatarUrl: 'https://picsum.photos/seed/patient10/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Atrial Fibrillation',
    followUp: 'Follow up in 2 weeks.',
    adherence: [],
    symptoms: [],
  },
  {
    id: '11',
    name: 'Kiran Desai',
    abhaId: '11-2233-4455-6677',
    age: 45,
    gender: 'Male',
    admissionDate: '2024-05-20',
    status: 'Admitted',
    avatarUrl: 'https://picsum.photos/seed/patient11/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Gastroenteritis',
    followUp: 'Follow up as needed.',
    adherence: [],
    symptoms: [],
  },
  {
    id: '12',
    name: 'Manju Devi',
    abhaId: '22-3344-5566-7788',
    age: 67,
    gender: 'Female',
    admissionDate: '2024-05-21',
    status: 'Reconciliation Pending',
    avatarUrl: 'https://picsum.photos/seed/patient12/100/100',
    vitals: [],
    medications: { preAdmission: [], postDischarge: [] },
    alerts: [],
    caregivers: [],
    abhaRecord: '',
    diagnosis: 'Urinary Tract Infection',
    followUp: 'Follow up in 1 week.',
    adherence: [],
    symptoms: [],
  }
];

export const getPatientById = (id: string) => {
  return patients.find(p => p.id === id);
};
